# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1648fb96c275ff81aa222bb780b77d8c7faa3de1a778819e7a4e83cccdef943cd5409548e16064e13028471e82dcaab45715ce7da5e5b3db770bfce2ff41302

test:
  secret_key_base: db14cd2714e55f79f63ccbf7979cbf048213b462a2624f9e25d29ab5c16bbf5428535d6e57ec00641b7a5cf59cd4681a659a8372c5a32b00a333e12eaaa98323

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
